# 使用するコンテナを記述する
services:
  web:
    # Dockerfileから作る
    build: .
    # flask_appという名前
    container_name: flask_app
    # フォルダを共有
    volumes:
      - ./src:/app
    restart: always

  nginx:
    # DockerHubから作る
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web