name: EC2 auto deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # BranchをCheckout
      - name: Checkout
        uses: actions/checkout@v2

      # デプロイする
      - name: Deploy
        run: |
          # SSH接続して、git pullする
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          # サーバーに接続してデプロイ
          ssh -o StrictHostKeyChecking=no -T -i private_key ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} << 'EOF'
            # アプリケーションディレクトリに移動
            cd ~/todo-app
            # Gitリポジトリから最新の変更を取得
            git pull origin main
          EOF
          # SSHのセキュリティグループを閉じる
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ env.IP }}/32
